src/main/java/org/jahia/modules/sam/healthcheck/probes/SearchIndexProbe.java, src/main/resources/META-INF/configurations/org.jahia.modules.sam.healthcheck.ProbesRegistry.cfg, tests/cypress/integration/api/checkProbes.spec.ts
…
https://jira.jahia.org/browse/TECH-987
Return a new probe of CRITICAL level:
`{
"name": "SearchIndex",
"severity": "CRITICAL",
"status": {
"health": "GREEN",
"message": "All indices are OK. Query AVG : 1.268 ms. [file=/var/jahia/repository/index is clean, sizeOfDirectory=445 KB, numberOfSegments=1].[file=/var/jahia/repository/workspaces/default/index is clean, sizeOfDirectory=8 MB, numberOfSegments=11].[file=/var/jahia/repository/workspaces/live/index is clean, sizeOfDirectory=7 MB, numberOfSegments=11]"
}
}`
=> TECH-987: Add new SearchIndexProbe returning statistics about index physical folders

src/main/java/org/jahia/modules/sam/healthcheck/probes/SearchIndexProbe.java
https://jira.jahia.org/browse/TECH-987
=> TECH-987: Fix threshold in red status message

.github/workflows/manual-run.yml, .github/workflows/nightly.yml, .github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, .github/workflows/on-release.yml, .github/workflows/on-rollback.yml
https://jira.jahia.org/browse/TECH-1081
Update deprecated steps
=> TECH-1081 Update deprecated steps

pom.xml, src/main/java/org/jahia/modules/sam/healthcheck/probes/ClusterConsistencyProbe.java, src/main/java/org/jahia/modules/sam/healthcheck/probes/ClusterProbeActivator.java, tests/.eslintrc.json, tests/cypress/e2e/api/moduleState.spec.ts, tests/cypress/fixtures/moduleStateProbe/start-channels.json, tests/cypress/fixtures/moduleStateProbe/start-seo.json, tests/cypress/fixtures/moduleStateProbe/stop-channels.json, tests/cypress/fixtures/moduleStateProbe/stop-seo.json
https://jira.jahia.org/browse/BACKLOG-20665
=> BACKLOG-20665: Add checks for cellar state

pom.xml
https://jira.jahia.org/browse/BACKLOG-20318
=> BACKLOG-20318: Update to released karaf cellar version

pom.xml, src/main/java/org/jahia/modules/sam/healthcheck/probes/ClusterConsistencyProbe.java
https://jira.jahia.org/browse/QA-14755
=> QA-14755: set context classloader to deserialize bundle entries

.github/workflows/on-merge.yml, .github/workflows/on-release.yml, pom.xml
https://jira.jahia.org/browse/TECH-1275
Add cyclonedx-maven-plugin and create/upload SBOMs on merge and release
The following are included in this PR
I have considered the following implications of my change:
=> TECH-1275: Add SBOM creation

.github/workflows/manual-run.yml, .github/workflows/nightly.yml, .github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, src/main/java/org/jahia/modules/sam/healthcheck/probes/DatastoreProbe.java, src/main/java/org/jahia/modules/sam/healthcheck/probes/FileDatastoreProbe.java, tests/cypress/plugins/ssh.ts, tests/env.run.sh, tests/package.json, tests/provisioning-manifest-build.yml, tests/reporter-config.json, tests/yarn.lock
https://jira.jahia.org/browse/QA-14945
=> QA-14945: Fix dataStore health probe always green

.github/workflows/manual-run.yml, .github/workflows/nightly.yml, .github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, src/main/java/org/jahia/modules/sam/healthcheck/probes/DatastoreProbe.java, src/main/java/org/jahia/modules/sam/healthcheck/probes/FileDatastoreProbe.java, tests/cypress/plugins/ssh.ts, tests/env.run.sh, tests/package.json, tests/provisioning-manifest-build.yml, tests/reporter-config.json, tests/yarn.lock
This PR cleans up a merge issue (no squash merge) from #89, all changes were approved and tests were already passing.
=> QA-14945 fix datastore health probe always green

pom.xml
=> QA-14945: Updated version in pom to 4.0.0-SNAPSHOT

.github/workflows/nightly.yml
=> TECH-1145: Fixed incorrect nightly workflow

.github/workflows/on-release.yml
https://jira.jahia.org/browse/BACKLOG-21549
=> BACKLOG-21549 - Add slack notif in the config

pom.xml
https://jira.jahia.org/browse/BACKLOG-21586
=> BACKLOG-21586 : revert version to 3.1.0-SNAPSHOT

.github/workflows/nightly.yml
=> Split pagerduty reporting between Jahia RL and Jahia SN

tests/.eslintrc.json, tests/ci.build.sh, tests/ci.startup.sh, tests/cypress/e2e/api/checkProbes.spec.ts, tests/cypress/e2e/api/moduleState.spec.ts, tests/cypress/e2e/api/shutdown.spec.ts, tests/cypress/fixtures/moduleStateProbe/start-bundle.json, tests/cypress/fixtures/moduleStateProbe/start-channels.json, tests/cypress/fixtures/moduleStateProbe/start-seo.json, tests/cypress/fixtures/moduleStateProbe/stop-bundle.json, tests/cypress/fixtures/moduleStateProbe/stop-channels.json, tests/cypress/fixtures/moduleStateProbe/stop-seo.json, tests/jahia-module/.gitignore, tests/jahia-module/pom.xml, tests/jahia-module/src/main/import/repository.xml, tests/jahia-module/src/main/java/org/jahia/modules/sam/test/DummyProbe.java, tests/jahia-module/src/main/resources/META-INF/definitions.cnd, tests/package.json, tests/provisioning-manifest-snapshot.yml, tests/yarn.lock
https://jira.jahia.org/browse/QA-14982
=> QA-14982 : add test

pom.xml
https://jira.jahia.org/browse/TECH-1578
=> TECH-1578: Bump version

tests/provisioning-manifest-snapshot.yml
=> BACKLOG-22318: SAM is now part of the build, no need to install

tests/jahia-module/pom.xml
https://jira.jahia.org/browse/TECH-1578
Update version of the test module to be in sync with the module version.
=> TECH-1578: Update SAM test module version

.github/workflows/on-code-change.yml, pom.xml, tests/cypress/e2e/api/jahiaErrors.spec.begin.ts, tests/jahia-module/pom.xml
=> BACKLOG-22396: Switched version to 3.1.0-SNAPSHOT to correct an inconsistency with versioning

src/main/java/org/jahia/modules/sam/healthcheck/probes/ModuleStateProbe.java
https://jira.jahia.org/browse/BACKLOG-22406
=> BACKLOG-22406: Check wiring issues as in ModuleManagement

tests/ci.build.sh, tests/ci.startup.sh
https://jira.jahia.org/browse/TECH-1710
=> TECH-1710: Use a fixed version of @jahia/cypress in scripts

src/main/java/org/jahia/modules/sam/healthcheck/probes/FileDatastoreProbe.java
https://jira.jahia.org/browse/BACKLOG-21616
Add a database connectivity check if datastore is in DB for FileDatastoreProbe
=> BACKLOG-21616: Add db check for datastore probe

src/main/java/org/jahia/modules/sam/healthcheck/probes/FileDatastoreProbe.java
https://jira.jahia.org/browse/BACKLOG-21616
Found issue during jahia-ee run test runs (I wasn't able to reproduce locally): https://github.com/Jahia/jahia-ee/actions/runs/9191303868
```
2024-05-23 00:30:00,248: ERROR [] - bundle org.apache.felix.scr:2.1.30 (70) Circular reference detected trying to get service [org.jahia.modules.sam.Probe]\n stack of references: ServiceReference: [org.jahia.modules.sam.Probe]\nServiceReference: [org.jahia.modules.sam.healthcheck.ProbesRegistry]\n
java.lang.Exception: stack trace
... suppressed 57 lines
at java.lang.Thread.run(Thread.java:833) ~[?:?]
2024-05-23 00:30:00,317: WARN  [ProbesRegistry] - bundle server-availability-manager:3.2.0.SNAPSHOT (131)[org.jahia.modules.sam.healthcheck.ProbesRegistry(77)] : Could not get service from ref …
```
=> BACKLOG-21616: Fix issue with OSGI service circular dependency

src/main/java/org/jahia/modules/sam/healthcheck/probes/RenderingChainProbe.java
https://jira.jahia.org/browse/BACKLOG-22634
=> BACKLOG-22634: Update messages

src/main/java/org/jahia/modules/sam/ProbeSeverity.java, src/main/java/org/jahia/modules/sam/graphql/GqlProbeSeverity.java, src/main/java/org/jahia/modules/sam/healthcheck/probes/JahiaErrorsProbe.java, src/main/resources/META-INF/configurations/org.jahia.modules.sam.healthcheck.ProbesRegistry.cfg, tests/cypress/e2e/api/jahiaErrors.spec.begin.ts, tests/cypress/fixtures/groovy/simpleFatalLog.groovy
…
https://jira.jahia.org/browse/BACKLOG-22925
Do not allow to configure. Check for FATAL, SEVERE, and ERROR.
The following are included in this PR
=> BACKLOG-22925: Lower priority of JahiaErrorsProbe. 

pom.xml, src/main/java/org/jahia/modules/sam/ProbeSeverity.java, src/main/java/org/jahia/modules/sam/graphql/GqlProbeSeverity.java, src/main/java/org/jahia/modules/sam/graphql/Load.java, src/main/java/org/jahia/modules/sam/healthcheck/probes/JahiaErrorsProbe.java, src/main/java/org/jahia/modules/sam/healthcheck/probes/ModuleStateProbe.java, src/main/java/org/jahia/modules/sam/healthcheck/probes/ServerLoadProbe.java, src/main/resources/META-INF/configurations/org.jahia.modules.sam.healthcheck.ProbesRegistry.cfg, tests/cypress/e2e/api/jahiaErrors.spec.begin.ts, tests/cypress/fixtures/groovy/simpleFatalLog.groovy, tests/cypress/fixtures/serverLoadProbe/set-default-threshold.json, tests/cypress/fixtures/serverLoadProbe/set-red-threshold.json, tests/cypress/fixtures/serverLoadProbe/set-yellow-threshold.json
(cherry picked from commit f8367dc7197f1275155a64810bbc76e0e8900f72)
https://jira.jahia.org/browse/BACKLOG-22406
=> BACKLOG-22406: Check wiring issues as in ModuleManagement (#115)

tests/package.json, tests/yarn.lock
https://jira.jahia.org/browse/TECH-1867
=> TECH-1867: Updated jahia-cypress to its latest version

.github/workflows/manual-run.yml, .github/workflows/nightly-release.yml, .github/workflows/nightly-snapshot.yml, .github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, .github/workflows/on-release.yml, .github/workflows/on-rollback.yml, .github/workflows/schedule-sonar.yml
https://jira.jahia.org/browse/TECH-1639
Upgrade actions
=> TECH-1639 Upgrade actions

src/main/java/org/jahia/modules/sam/graphql/GqlProbe.java
https://jira.jahia.org/browse/QA-15262
When a probe status is called over cluster and a node does not respond, the exception encapsulated in a FailingMap cause an exception as soons as a method is called on it (size()) in GqlProbe
The following are included in this PR
I have considered the following implications of my change:
=> QA-15262: Catch remote bundle information exception when calling probe status.

pom.xml, tests/jahia-module/pom.xml
https://jira.jahia.org/browse/BACKLOG-23155
=> BACKLOG-23155: Downgraded module version from 3.3.0-SN to 3.2.1-SN

pom.xml
https://jira.jahia.org/browse/BACKLOG-23154
=> BACKLOG-23155: Downgraded module version from 2.9.0-SN to 2.8.1-SN

src/main/java/org/jahia/modules/sam/healthcheck/probes/SupportedStackJSModulesProbe.java
https://jira.jahia.org/browse/BACKLOG-23366
Migrate from `org.jahia.modules:npm-modules-engine` to `org.jahia.modules:javascript-modules-engine`.
=> BACKLOG-23366: Migrate to javascript-modules-engine

src/main/java/org/jahia/modules/sam/healthcheck/HealthCheckServlet.java, src/main/java/org/jahia/modules/sam/healthcheck/probes/ModulesSpringUsageProbe.java, src/main/java/org/jahia/modules/sam/healthcheck/probes/ServerLoadProbe.java, src/main/java/org/jahia/modules/sam/healthcheck/probes/SupportedStackJSModulesProbe.java, src/main/java/org/jahia/modules/sam/load/LoadAverageServiceImpl.java
Address critical issues reported by SonarQube: https://sonarqube.jahia.com/project/issues?resolved=false&severities=CRITICAL&id=org.jahia.modules%3Aserver-availability-manager.
=> refactor: Address critical SonarQube issues

.github/workflows/manual-run.yml, .github/workflows/nightly-release.yml, .github/workflows/nightly-snapshot.yml, .github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, .github/workflows/on-release.yml, .github/workflows/schedule-sonar.yml
Update the Github actions to use as much as possible the reusable workflows, and keep the parameters to the bare minimum.
> [!TIP]
> Documentation to guide the reviews: [How to do a code review](https://jahia-confluence.atlassian.net/wiki/spaces/PR/pages/2064660/How+to+do+a+code+review+-+Ref+ISSOP08.A14006)
=> ci: Base Github actions on reusable workflows

src/main/java/org/jahia/modules/sam/healthcheck/probes/JahiaErrorsProbe.java, src/main/java/org/jahia/modules/sam/healthcheck/probes/MultipleBundleVersions.java, src/main/java/org/jahia/modules/sam/healthcheck/probes/SupportedStackJSModulesProbe.java, src/main/java/org/jahia/modules/sam/healthcheck/probes/SupportedStackJVMProbe.java
Remove unused Java imports.
> [!TIP]
> Documentation to guide the reviews: [How to do a code review](https://jahia-confluence.atlassian.net/wiki/spaces/PR/pages/2064660/How+to+do+a+code+review+-+Ref+ISSOP08.A14006)
=> style: Remove unused imports
